---
- hosts: 192.168.0.104
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Add details to FMG
     fmgr_dvm_cmd_add_device:
        bypass_validation: False
        dvm_cmd_add_device:
           adom: SD-WAN-Lab
           device:
              device action: add_model
              adm_usr: "{{username}}"
              mgmt_mode: fmgfaz
              name: "{{system-name}}"
              os_type: fos
              os_ver: '6.0'
              mr: '4'
              platform_str: "{{model}}"
              sn: "{{SN}}"
           groups: 
             -
                  name: "{{Group}}"
                  adom: SD-WAN-Lab
