---
- hosts: 192.168.0.104
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: no description
     fmgr_dynamic_interface:
        adom: SD-WAN-Lab
        state: present
        dynamic_interface:
           color: Green
           default-mapping: enable
           defmap-intf: Port3
           description: <value of string>
           dynamic_mapping:
             -
                 _scope:
                   -
                       name: Warehouse_1
                       vdom: root
                 local-intf: internal
                   
                       name: Branch_1
                       vdom: root
                 local-intf: port3
                   
                       name: Branch_2
                       vdom: root
                 local-intf: port3
                    
                       name: AWS-FGT
                       vdom: root
                 local-intf: port2                
                     
                       name: Warehouse_1
                       vdom: root
                 local-intf: internal
                     
                       name: fgt-warehouse-ansible
                       vdom: root
                 local-intf: internal                 
           name: Branch-LAN
