---
- hosts: 192.168.0.104
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
    -   name: 'Branch-LAN'
        fmgr_generic:
             json: |
                  {
                   "method":"update",
                   "params": [
                    {
                        "url": "/pm/config/adom/SD-WAN-Lab/obj/dynamic/interface/",
                        "data": {
                           "name": "Branch-LAN",
                           "description": "Branc-LAN",
                           "default-mapping": "1",
                           "defmap-intf": "port3",                           
                           "dynamic_mapping": [
                                {
                                    "_scope": {
                                        "name": "Warehouse_1",
                                        "vdom": "root"
                                    }
                                    "local-intf": "internal"
                                }
                                              ]
                                }
                    }
                              ]
                  }
