---
- hosts: 192.168.0.104
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Branch-LAN
     fmgr_dynamic_interface:
        adom: SD-WAN-Lab
        state: present
        dynamic_interface:
           color: '11'
           default-mapping: enable
           defmap-intf: port3
           description: Branch-LAN
           dynamic_mapping:
             -
                 _scope:{
                   -
                       name: Warehouse_1
                       vdom: root
					 }  
                       local-intf: internal

                 _scope:{
                   -
                       name: Branch_1
                       vdom: root
					  } 
                       local-intf: port3                 

                 _scope:{
                   -
                       name: Branch_2
                       vdom: root
					  } 
                       local-intf: port3                  

                 _scope:{
                   -
                       name: AWS-FGT
                       vdom: root
					  } 
                       local-intf: port2

                 _scope:{
                   -
                       name: fgt-warehouse-ansible
                       vdom: root
					  } 
                       local-intf: internal
                 
           name: Branch-LAN
