---
- hosts: 192.168.0.104
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
    -   name: Script Template Update
        fmgr_generic:
            json: |
                     {
      "url": "/pm/config/adom/{{adom}}/obj/cli/template-group",
      "data": {
        "name": "Warehouse-New",
        "member": [
          "Warehouse-New-Overlay",
          "Warehouse-New-BGP"
          ],
        "scope member": [
          {
            "name": "fgt-warehouse-ansible",
            "vdom": "root"
          },
        ]
      }
    }
  ]
