---
- hosts: 192.168.0.104
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
    -   name: 'login a user'
        fmgr_generic:
             method: 'update'
             params:
                - url: '/pm/config/adom/SD-WAN-Lab/obj/cli/template-group'
                  "data": {
        "name": "Warehouse-New",
        "member": [
          "Warehouse-New-Overlay",
          "Warehouse-New-BGP"
          ],
        "scope member": [
          {
            "name": "{{name_fgt_ztp}}",
            "vdom": "root"
          },
        ]
      }
    }
  ]
}
