---
- hosts: 192.168.0.104
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Set Details
     fmgr_dvmdb_device:
        bypass_validation: False
        adom: SD-WAN-Lab
        device: "{{devicename}}"
        dvmdb_device:
           hostname: "{{devicename}}"
           latitude: "{{latitude}}"
           longitude: "{{longitude}}"
           meta fields: 
              address: "{{citycountry}}"
              branch-id: "{{branchid}}"
              remote-dc-id:
              LAN-IP: "{{LANIP}}"
              BGP-code: "{{networksubnet}}"
           name: "{{devicename}}"
