---
- hosts: 192.168.0.104
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Add Details
     fmgr_dvmdb_device:
        bypass_validation: False
        adom: SD-WAN-Lab
        device: "{{Device-Name}}"
        dvmdb_device:
           hostname: "{{fgt-warehouse-ansible}}"
           latitude: "{{latitiude}}"
           longitude: "{{longtidue}}"
           meta fields: 
              address: "{{city, country}}"
              branch-id: "{{branch-id}}"
              BGP-code: "{{Branch Subnet}}"
           name: "{{Device-Name}}"
