- hosts: 192.168.0.104
  collections:
    - fortinet.fortimanager
  connection: httpapi
  vars:
     ansible_httpapi_use_ssl: True
     ansible_httpapi_validate_certs: False
     ansible_httpapi_port: 443
  tasks:
   - name: Add a device to the Device Manager database.
     fmgr_dvm_cmd_add_device:
        dvm_cmd_add_device:
           adom: SD-WAN-Lab
           device:
              adm_pass: fgtadmin
              mgmt_mode: fmgfaz
              name: fgt-warehouse-ansible
              os_type: fos
              os_ver: '6.0'
              platform_str: Fortigate-81-POE
              sn: FG81EPTK19002078
           flags:
             - none
           groups:
             -
                 name: warehouse
                 vdom: SD-WAN-Lab

